# Generated by Django 4.1 on 2022-09-14 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_options_alter_group_group_desc_and_more'),
        ('accounts', '0002_group_group_accounts_group_ux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_group_set', to='menu.group', verbose_name='그룹아이디'),
        ),
        migrations.AlterField(
            model_name='group',
            name='use_yn',
            field=models.CharField(max_length=1, verbose_name='사용여부'),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_user_set', to=settings.AUTH_USER_MODEL, verbose_name='사용자아이디'),
        ),
    ]
