# Generated by Django 4.1 on 2022-09-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_group_group_alter_group_use_yn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '계정그룹정보'},
        ),
    ]
