# Generated by Django 4.1 on 2022-09-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '계정그룹정보', 'verbose_name_plural': '계정그룹정보'},
        ),
    ]
