# Generated by Django 4.1 on 2022-09-14 15:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(
                    max_length=10, primary_key=True, serialize=False)),
                ('group_nm', models.CharField(max_length=30)),
                ('group_desc', models.CharField(max_length=1000)),
                ('ord_seq', models.IntegerField()),
                ('use_yn', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(
                    max_length=10, primary_key=True, serialize=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='children', to='menu.menu', verbose_name='parent')),
                ('menu_url', models.CharField(max_length=1000)),
                ('level', models.IntegerField()),
                ('ord_seq', models.IntegerField()),
                ('use_yn', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='menu_group_set', to='menu.group')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='menu_set', to='menu.menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'menu_auth',
            },
        ),
        migrations.AddConstraint(
            model_name='menuauth',
            constraint=models.UniqueConstraint(
                fields=('menu', 'group'), name='menu_group_ux'),
        ),
    ]
