# Generated by Django 4.1 on 2022-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_nm',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
